# Application and Spring configuration for production

spring:
  mail:
    properties.mail.smtp:
      auth: true
      starttls:
        enable: true

app:
  jwt:
    cookie:
      secure: true

  environment: PROD

logging:
  level:
    root: WARN
    com.openclassrooms.mddapi: INFO
    org.springframework: WARN
    org.springframework.security: WARN